### ISSUE TITLE
Allow message to be displayed "User already in this gamemode" when user is in selected gamemode

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/zander#4]
Check adventure.java and see comment.

**Comment by jasoryeh** [comment]
Should already be done?

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/56464864-053bbc80-63a7-11e9-82f1-f67d49692773.png)

**Comment by jasoryeh** [comment]
Has been fixed.
