### ISSUE TITLE
Error in Discord profile command.

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/zander#50]
https://github.com/shadowolfyt/zander/blob/master/src/main/java/com/shadowolfyt/zander/discord/profile.java

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/58385001-30658d00-7f9f-11e9-95b5-a792af5837e4.png)

Looks like you don't have a "leaves" column... I assume this is a count of how many times the player has left the server?

**Comment by shadowolfyt** [comment]
I fixed that now. I have this error now: https://gyazo.com/b4e6042d023e48a0478324cc1c069e80

**Comment by jasoryeh** [comment]
> I fixed that now. I have this error now: https://gyazo.com/b4e6042d023e48a0478324cc1c069e80

Could also be when your db has nothing in that column for that person... Make sure there are all the columns that you are looking in.

**Comment by shadowolfyt** [comment]
It seems to dislike this line: `PreparedStatement findstatement = plugin.getConnection().prepareStatement("SELECT * FROM playerdata WHERE username=?");
`
I don't see anything wrong with the statement.

**Comment by jasoryeh** [comment]
Maybe because you don’t have integers in your dB? And in your profile in
you are looking for integers.

**Comment by shadowolfyt** [comment]
Good idea to make joins and deaths an int?

**Comment by jasoryeh** [comment]
Shouldnt even be a question.

**Comment by shadowolfyt** [comment]
It still keeps failing on Line 33 even with the string change.

**Comment by shadowolfyt** [comment]
I seriously can't get this one to work. Apparently it has nothing to do with the SQL and something to do with not listening to the class.
