### ISSUE TITLE
[WhitelistListGUI] The .getname is deprecated.

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/zander#74]

**Comment by jasoryeh** [comment]
![image](https://user-images.githubusercontent.com/13290941/58377914-109e7c80-7f3f-11e9-9674-ddb415aa9627.png)

From Choco @ SpigotMC https://www.spigotmc.org/threads/any-ways-to-check-inventory-name-in-1-14.369869/#post-3377594
