### ISSUE TITLE
Things and commands that contain a GUI completely break the inventory.

### ISSUE THREAD

**Issue by shadowolfyt** [shadowolfyt/zander#75]

**Comment by shadowolfyt** [comment]
@jasoryeh would you be able to look at this because I have no actual clue what the issue is.

**Comment by jasoryeh** [comment]
How so?

**Comment by jasoryeh** [comment]
Oops wrong button.

**Comment by shadowolfyt** [comment]
I've updated the plugin to the latest in Spigot in 1.14. 
#74 caused an issue which I commented out but didn't fix it.
Now the events in the GUI won't let me get blocks or anything into my inventory or middle click blocks, it makes the inventory unusable.

**Comment by jasoryeh** [comment]
All commands? Maybe try redownloading...

**Comment by shadowolfyt** [comment]
> All commands? Maybe try redownloading...

It's only when the GUI classes are in there, all of the inventory and stuff breaks.

**Comment by shadowolfyt** [comment]
> > All commands? Maybe try redownloading...
> 
> It's only when the GUI classes are in there, all of the inventory and stuff breaks.

https://gyazo.com/401a1d90187f7b0c04e6ea317bdb3860

**Comment by jasoryeh** [comment]
Maybe try putting some debug messages in all of your event listeners so you can identify which ones are making you close the inventory...

**Comment by shadowolfyt** [comment]
Fixing the deprecation with #74 seemed to fix this, what the heck?
